services:
  - type: web
    name: robertofausto
    runtime: python
    buildCommand: pip install -r requirements.txt && pybabel compile -d translations
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
